name: snap_study
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  http: ^0.13.6
  file_picker: ^6.1.1
  intl: ^0.18.1  # ✅ For date formatting

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/bear.png
    - assets/upload_icon.png
    - assets/bear_learning.png
    - assets/bear_pdf.png
    - assets/bear_music.png
    - assets/bear_favorite.png
    - assets/bear_tools.png
    - assets/login_tobi.png
    - assets/register_tobi.png
